version: '3.8'
# Docker Compose 파일 버전 - 애플리케이션 스택 전용

services:
  # ========== Spring Boot 애플리케이션 ==========
  app:
    # ✨ [핵심] CI/CD 파이프라인에서는 APP_IMAGE_URI 환경변수를 주입받아 ECR 이미지를 사용합니다.
    # 로컬 환경에서는 이 변수가 없으므로 build: . 설정을 통해 이미지를 직접 빌드합니다.
    image: ${APP_IMAGE_URI:-aod-app:latest}
    container_name: aod-app
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      TZ: Asia/Seoul
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Seoul"
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE:-prod}

      # ✨ [핵심 수정] 외부 DB 및 Selenium을 참조하도록 환경 변수 사용
      # 이 값들은 GitHub Actions Secrets를 통해 주입됩니다.
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      SELENIUM_URL: ${SELENIUM_URL}
      TMDB_API_KEY: ${TMDB_API_KEY}
      NAVER_ID: ${NAVER_ID}
      NAVER_PW: ${NAVER_PW}
      NETFLIX_ID: ${NETFLIX_ID}
      NETFLIX_PW: ${NETFLIX_PW}

    networks:
      - aod-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# ========== 네트워크 정의 ==========
# 다른 스택(예: 모니터링)과 통신이 필요할 경우 external network로 변경할 수 있습니다.
networks:
  aod-network:
    driver: bridge
