version: '3.8'

services:
  app:
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xms2g -Xmx4g -XX:+UseG1GC"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

  prometheus:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  grafana:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M