version: '3.8'

services:
  app:
    environment:
      SPRING_PROFILES_ACTIVE: local
    ports:
      - "8080:8080"
      - "5005:5005"
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "/app/app.jar"]

  prometheus:
    restart: "no"

  grafana:
    restart: "no"

  alertmanager:
    restart: "no"