

services:
  app:
    environment:
      SPRING_PROFILES_ACTIVE: local
      # 로컬 환경에서는 local 프로파일 사용
      # → application-local.properties 읽음
    ports:
      - "8080:8080"
      - "5005:5005" # 디버그 포트 추가
      # IntelliJ에서 Remote Debug 연결 가능
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "/app/app.jar"]
    # JDWP (Java Debug Wire Protocol) 활성화
    # suspend=n: 디버거 연결 없어도 앱 시작
    # address=*:5005: 모든 IP에서 5005 포트로 디버그 연결 허용
  prometheus:
    restart: "no"
    # 로컬에서는 자동 재시작 안함
    # 개발 중 수동으로 제어하기 위해
  grafana:
    restart: "no"

  alertmanager:
    restart: "no"