version: '3.8'
# 모니터링 스택 공통 설정 파일

services:
  # ========== Prometheus (메트릭 수집) ==========
  prometheus:
    image: prom/prometheus:latest
    container_name: aod-prometheus
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    networks:
      - aod-network
    restart: unless-stopped

  # ========== Grafana (시각화) ==========
  grafana:
    image: grafana/grafana:latest
    container_name: aod-grafana
    ports:
      - "${GRAFANA_PORT:-3001}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL:-http://localhost:3001}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - aod-network
    restart: unless-stopped
    depends_on:
      - prometheus

  # ========== Alertmanager (알림 관리) ==========
  alertmanager:
    image: prom/alertmanager:latest
    container_name: aod-alertmanager
    ports:
      - "${ALERTMANAGER_PORT:-9093}:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager-data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - aod-network
    restart: unless-stopped

# ========== 네트워크 및 볼륨 정의 ==========
networks:
  aod-network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data: