global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'aod-crawler'

rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app-blue:8080', 'app-green:8080']
        labels:
          application: 'aod-crawler'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']